// import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';

// import './globals.css';

// const geistSans = Geist({
//   variable: '--font-geist-sans',
//   subsets: ['latin'],
// });

// const geistMono = Geist_Mono({
//   variable: '--font-geist-mono',
//   subsets: ['latin'],
// });

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang='en'>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';

import './globals.css';
import Footer from '@/components/Footer';

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // Можно добавить другие веса, например '300', '900'
  variable: '--font-roboto', // Переменная для кастомных стилей в CSS
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'smllns-games',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.variable} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}
